In [1]:
import sqlite3                                       # Creating a new database and cursor.
dbcon=sqlite3.connect("Mycapstoneprojectdb.db")
cur=dbcon.cursor()

# Creating Table 1: Sno, MovieName, Director Name, Duration, genre, ratings

In [25]:
cur.execute("create table A(Sno int, MovieName text primarykey, Director1 text,Director2 text, Director3 text, Duration int, Year int, Ratings real, Metascore int)")

In [26]:
with open('Movielist.csv','r') as file:                # Inserting the values from csv file to table.
    result=0
    for row in file:
        cur.execute("insert into A values(?,?,?,?,?,?,?,?,?)",row.split(','))
        dbcon.commit()
        result+=1
print(result,"rows inserted")

50 rows inserted

In [2]:
# 1)  Display all the details of movies created by directors Christopher and Matt Reeves.
results=cur.execute('select * from A where Director1 like "Christopher%" or "Matt Reeves"')
results.fetchall()

[(1, 'The Dark Knight', 'Christopher Nolan', 'NA', 'NA', 152, 2008, 9.0, 84),
 (4, 'Inception', 'Christopher Nolan', 'NA', 'NA', 148, 2010, 8.8, 74),
 (19,
  'The Dark Knight Rises',
  'Christopher Nolan',
  'NA',
  'NA',
  164,
  2012,
  8.4,
  78),
 (39, 'Batman Begins', 'Christopher Nolan', 'NA', 'NA', 140, 2005, 8.2, 70)]

In [30]:
# 2) Display all the details of movies with a duration of 140 minutes to 190 minutes.
results=cur.execute('select * from A where Duration between 140 and 190')
results.fetchall()

[(1, 'The Dark Knight', 'Christopher Nolan', 'NA', 'NA', 152, 2008, 9.0, 84),
 (3,
  'Spider-Man: Across the Spider-Verse',
  'Joaquim Dos Santos',
  'Kemp Powers',
  'Justin K. Thompson',
  140,
  2023,
  8.9,
  86),
 (4, 'Inception', 'Christopher Nolan', 'NA', 'NA', 148, 2010, 8.8, 74),
 (5,
  'The Lord of the Rings: The Fellowship of the Ring',
  'Peter Jackson',
  'NA',
  'NA',
  178,
  2001,
  8.8,
  92),
 (6,
  'The Lord of the Rings: The Two Towers',
  'Peter Jackson',
  'NA',
  'NA',
  179,
  2002,
  8.8,
  87),
 (9, 'Soorarai Pottru', 'Sudha Kongara', 'NA', 'NA', 153, 2020, 8.7, 'NA\n'),
 (14, 'Sita Ramam', 'Hanu Raghavapudi', 'NA', 'NA', 163, 2022, 8.6, 'NA\n'),
 (15, 'Gladiator', 'Ridley Scott', 'NA', 'NA', 155, 2000, 8.5, 67),
 (19,
  'The Dark Knight Rises',
  'Christopher Nolan',
  'NA',
  'NA',
  164,
  2012,
  8.4,
  78),
 (20,
  'Avengers: Endgame',
  'Anthony Russo',
  'Joe Russo',
  'NA',
  181,
  2019,
  8.4,
  78),
 (23,
  'Avengers: Infinity War',
  'Anthony Russo',
  'Joe Russo',
  'NA',
  149,
  2018,
  8.4,
  68),
 (24, 'Kaithi', 'Lokesh Kanagaraj', 'NA', 'NA', 145, 2019, 8.4, 'NA\n'),
 (25, 'Asuran', 'Vetrimaaran', 'NA', 'NA', 141, 2019, 8.4, 'NA\n'),
 (27, 'Heat', 'Michael Mann', 'NA', 'NA', 170, 1995, 8.3, 76),
 (31, 'Dangal', 'Nitesh Tiwari', 'NA', 'NA', 161, 2016, 8.3, 'NA\n'),
 (32, 'Kantara', 'Rishab Shetty', 'NA', 'NA', 148, 2022, 8.3, 'NA\n'),
 (33,
  'K.G.F: Chapter 2',
  'Prashanth Neel',
  'NA',
  'NA',
  168,
  2022,
  8.3,
  'NA\n'),
 (34, 'Vikram', 'Lokesh Kanagaraj', 'NA', 'NA', 175, 2022, 8.3, 'NA\n'),
 (36, 'Raatchasan', 'Ram Kumar', 'NA', 'NA', 170, 2018, 8.3, 'NA\n'),
 (39, 'Batman Begins', 'Christopher Nolan', 'NA', 'NA', 140, 2005, 8.2, 70),
 (40, 'Spider-Man: No Way Home', 'Jon Watts', 'NA', 'NA', 148, 2021, 8.2, 71),
 (45, 'Ran', 'Akira Kurosawa', 'NA', 'NA', 162, 1985, 8.2, 97),
 (47,
  'Baahubali 2: The Conclusion',
  'S.S. Rajamouli',
  'NA',
  'NA',
  167,
  2017,
  8.2,
  'NA\n')]

In [31]:
# 3) Display all details of movies with ratings above 7 in ascending order.
results=cur.execute('Select * from A where Ratings>7 order by Ratings') 
results.fetchall()

[(37,
  'Indiana Jones and the Last Crusade',
  'Steven Spielberg',
  'NA',
  'NA',
  127,
  1989,
  8.2,
  65),
 (38, 'Jurassic Park', 'Steven Spielberg', 'NA', 'NA', 127, 1993, 8.2, 68),
 (39, 'Batman Begins', 'Christopher Nolan', 'NA', 'NA', 140, 2005, 8.2, 70),
 (40, 'Spider-Man: No Way Home', 'Jon Watts', 'NA', 'NA', 148, 2021, 8.2, 71),
 (41, '1917', 'Sam Mendes', 'NA', 'NA', 119, 2019, 8.2, 78),
 (42, 'Die Hard', 'John McTiernan', 'NA', 'NA', 132, 1988, 8.2, 72),
 (43,
  'Kill Bill: Vol. 1',
  'Quentin Tarantino',
  'NA',
  'NA',
  111,
  2003,
  8.2,
  69),
 (44, 'V for Vendetta', 'James McTeigue', 'NA', 'NA', 132, 2005, 8.2, 62),
 (45, 'Ran', 'Akira Kurosawa', 'NA', 'NA', 162, 1985, 8.2, 97),
 (46,
  'Demon Slayer the Movie: Mugen Train',
  'Haruo Sotozaki',
  'NA',
  'NA',
  117,
  2020,
  8.2,
  72),
 (47,
  'Baahubali 2: The Conclusion',
  'S.S. Rajamouli',
  'NA',
  'NA',
  167,
  2017,
  8.2,
  'NA\n'),
 (48, 'Gangs of Wasseypur', 'Anurag Kashyap', 'NA', 'NA', 321, 2012, 8.2, 89),
 (49, 'Yojimbo', 'Akira Kurosawa', 'NA', 'NA', 110, 1961, 8.2, 93),
 (50,
  'Uri: The Surgical Strike',
  'Aditya Dhar',
  'NA',
  'NA',
  138,
  2019,
  8.2,
  'NA\n'),
 (26, 'Top Gun: Maverick', 'Joseph Kosinski', 'NA', 'NA', 130, 2022, 8.3, 78),
 (27, 'Heat', 'Michael Mann', 'NA', 'NA', 170, 1995, 8.3, 76),
 (28,
  'Star Wars: Episode VI - Return of the Jedi',
  'Richard Marquand',
  'NA',
  'NA',
  131,
  1983,
  8.3,
  58),
 (29, 'Princess Mononoke', 'Hayao Miyazaki', 'NA', 'NA', 134, 1997, 8.3, 76),
 (30,
  'North by Northwest',
  'Alfred Hitchcock',
  'NA',
  'NA',
  136,
  1959,
  8.3,
  98),
 (31, 'Dangal', 'Nitesh Tiwari', 'NA', 'NA', 161, 2016, 8.3, 'NA\n'),
 (32, 'Kantara', 'Rishab Shetty', 'NA', 'NA', 148, 2022, 8.3, 'NA\n'),
 (33,
  'K.G.F: Chapter 2',
  'Prashanth Neel',
  'NA',
  'NA',
  168,
  2022,
  8.3,
  'NA\n'),
 (34, 'Vikram', 'Lokesh Kanagaraj', 'NA', 'NA', 175, 2022, 8.3, 'NA\n'),
 (35, 'Shershaah', 'Vishnuvardhan', 'NA', 'NA', 135, 2021, 8.3, 'NA\n'),
 (36, 'Raatchasan', 'Ram Kumar', 'NA', 'NA', 170, 2018, 8.3, 'NA\n'),
 (17,
  'Raiders of the Lost Ark',
  'Steven Spielberg',
  'NA',
  'NA',
  115,
  1981,
  8.4,
  85),
 (18,
  'Spider-Man: Into the Spider-Verse',
  'Bob Persichetti',
  'Peter Ramsey',
  'Rodney Rothman',
  117,
  2018,
  8.4,
  87),
 (19,
  'The Dark Knight Rises',
  'Christopher Nolan',
  'NA',
  'NA',
  164,
  2012,
  8.4,
  78),
 (20,
  'Avengers: Endgame',
  'Anthony Russo',
  'Joe Russo',
  'NA',
  181,
  2019,
  8.4,
  78),
 (21, 'Aliens', 'James Cameron', 'NA', 'NA', 137, 1986, 8.4, 84),
 (22, 'Oldboy', 'Park Chan-wook', 'NA', 'NA', 101, 2003, 8.4, 77),
 (23,
  'Avengers: Infinity War',
  'Anthony Russo',
  'Joe Russo',
  'NA',
  149,
  2018,
  8.4,
  68),
 (24, 'Kaithi', 'Lokesh Kanagaraj', 'NA', 'NA', 145, 2019, 8.4, 'NA\n'),
 (25, 'Asuran', 'Vetrimaaran', 'NA', 'NA', 141, 2019, 8.4, 'NA\n'),
 (15, 'Gladiator', 'Ridley Scott', 'NA', 'NA', 155, 2000, 8.5, 67),
 (16, 'LÃ©on: The Professional', 'Luc Besson', 'NA', 'NA', 110, 1994, 8.5, 64),
 (10,
  'Terminator 2: Judgment Day',
  'James Cameron',
  'NA',
  'NA',
  137,
  1991,
  8.6,
  75),
 (11,
  'Star Wars: Episode IV - A New Hope',
  'George Lucas',
  'NA',
  'NA',
  121,
  1977,
  8.6,
  90),
 (12, 'Seven Samurai', 'Akira Kurosawa', 'NA', 'NA', 207, 1954, 8.6, 98),
 (13, 'Harakiri', 'Masaki Kobayashi', 'NA', 'NA', 133, 1962, 8.6, 85),
 (14, 'Sita Ramam', 'Hanu Raghavapudi', 'NA', 'NA', 163, 2022, 8.6, 'NA\n'),
 (7,
  'The Matrix',
  'Lana Wachowski',
  'Lilly Wachowski',
  'NA',
  136,
  1999,
  8.7,
  73),
 (8,
  'Star Wars: Episode V - The Empire Strikes Back',
  'Irvin Kershner',
  'NA',
  'NA',
  124,
  1980,
  8.7,
  82),
 (9, 'Soorarai Pottru', 'Sudha Kongara', 'NA', 'NA', 153, 2020, 8.7, 'NA\n'),
 (4, 'Inception', 'Christopher Nolan', 'NA', 'NA', 148, 2010, 8.8, 74),
 (5,
  'The Lord of the Rings: The Fellowship of the Ring',
  'Peter Jackson',
  'NA',
  'NA',
  178,
  2001,
  8.8,
  92),
 (6,
  'The Lord of the Rings: The Two Towers',
  'Peter Jackson',
  'NA',
  'NA',
  179,
  2002,
  8.8,
  87),
 (3,
  'Spider-Man: Across the Spider-Verse',
  'Joaquim Dos Santos',
  'Kemp Powers',
  'Justin K. Thompson',
  140,
  2023,
  8.9,
  86),
 (1, 'The Dark Knight', 'Christopher Nolan', 'NA', 'NA', 152, 2008, 9.0, 84),
 (2,
  'The Lord of the Rings: The Return of the King',
  'Peter Jackson',
  'NA',
  'NA',
  201,
  2003,
  9.0,
  94)]

In [32]:
# 4) Display all movie names in descending order.
results=cur.execute("select MovieName from A order by MovieName desc")
results.fetchall()

[('Yojimbo',),
 ('Vikram',),
 ('V for Vendetta',),
 ('Uri: The Surgical Strike',),
 ('Top Gun: Maverick',),
 ('The Matrix',),
 ('The Lord of the Rings: The Two Towers',),
 ('The Lord of the Rings: The Return of the King',),
 ('The Lord of the Rings: The Fellowship of the Ring',),
 ('The Dark Knight Rises',),
 ('The Dark Knight',),
 ('Terminator 2: Judgment Day',),
 ('Star Wars: Episode VI - Return of the Jedi',),
 ('Star Wars: Episode V - The Empire Strikes Back',),
 ('Star Wars: Episode IV - A New Hope',),
 ('Spider-Man: No Way Home',),
 ('Spider-Man: Into the Spider-Verse',),
 ('Spider-Man: Across the Spider-Verse',),
 ('Soorarai Pottru',),
 ('Sita Ramam',),
 ('Shershaah',),
 ('Seven Samurai',),
 ('Ran',),
 ('Raiders of the Lost Ark',),
 ('Raatchasan',),
 ('Princess Mononoke',),
 ('Oldboy',),
 ('North by Northwest',),
 ('LÃ©on: The Professional',),
 ('Kill Bill: Vol. 1',),
 ('Kantara',),
 ('Kaithi',),
 ('K.G.F: Chapter 2',),
 ('Jurassic Park',),
 ('Indiana Jones and the Last Crusade',),
 ('Inception',),
 ('Heat',),
 ('Harakiri',),
 ('Gladiator',),
 ('Gangs of Wasseypur',),
 ('Die Hard',),
 ('Demon Slayer the Movie: Mugen Train',),
 ('Dangal',),
 ('Batman Begins',),
 ('Baahubali 2: The Conclusion',),
 ('Avengers: Infinity War',),
 ('Avengers: Endgame',),
 ('Asuran',),
 ('Aliens',),
 ('1917',)]

In [33]:
# 5) Display movie name starts with ‘P’ and their rating is greater than 7.
results=cur.execute('select MovieName from A where MovieName like "P%" and Ratings>7')
results.fetchall()

[('Princess Mononoke',)]

# Creating Table 2: Movie Name, stars, votes, Genre, Gross collection, popularity, Certification

In [34]:
cur.execute("create table B(MovieName text, Stars1 text, Stars2 text, Stars3 text, Votes int, Genre1 text, Genre2 text, Genre3 text, Gross varchar, Popularity int, Certification varchar,foreign key(MovieName) references A(MovieName))")

In [35]:
with open('Movie_full_details.csv','r') as file1:          # Insering values from csv file to table.
    result1=0
    for rows in file1:
        cur.execute("insert into B values(?,?,?,?,?,?,?,?,?,?,?)",rows.split(','))
        dbcon.commit()
        result1+=1
print(result1,"rows inserted")

50 rows inserted

In [37]:
# 1) Display all movie names with star Arnold Schwarzenegger in ascending order.
results1=cur.execute('select MovieName,Stars1 from B where Stars1="Arnold Schwarzenegger" order by MovieName asc')
results1.fetchall()

[('Terminator 2: Judgment Day', 'Arnold Schwarzenegger')]

In [69]:
# 2) Display all details of the movie with the highest number of votes.
results1=cur.execute('select * from B where votes=(select max(Votes) from B)')
results1.fetchall()

[('The Dark Knight',
  'Christian Bale',
  'Heath Ledger',
  'Aaron Eckhart',
  2746898,
  'Action',
  'Crime',
  'Drama',
  ' 534.86M',
  39,
  'PG-13\n')]

In [15]:
# 3) Display movie names with gross collections in descending order.
results1=cur.execute('select MovieName,Gross from B2 order by MovieName desc')
results1.fetchall()

[('Yojimbo', 'NA'),
 ('Vikram', 'NA'),
 ('V for Vendetta', ' 70.51M'),
 ('Uri: The Surgical Strike', ' 4.19M'),
 ('Top Gun: Maverick', ' 718.73M'),
 ('The Matrix', ' 171.48M'),
 ('The Lord of the Rings: The Two Towers', ' 342.55M'),
 ('The Lord of the Rings: The Return of the King', ' 377.85M'),
 ('The Lord of the Rings: The Fellowship of the Ring', ' 315.54M'),
 ('The Dark Knight Rises', ' 448.14M'),
 ('The Dark Knight', ' 534.86M'),
 ('Terminator 2: Judgment Day', ' 204.84M'),
 ('Star Wars: Episode VI - Return of the Jedi', ' 309.13M'),
 ('Star Wars: Episode V - The Empire Strikes Back', ' 290.48M'),
 ('Star Wars: Episode IV - A New Hope', ' 322.74M'),
 ('Spider-Man: No Way Home', ' 804.75M'),
 ('Spider-Man: Into the Spider-Verse', ' 190.24M'),
 ('Spider-Man: Across the Spider-Verse', 'NA'),
 ('Soorarai Pottru', 'NA'),
 ('Sita Ramam', 'NA'),
 ('Shershaah', 'NA'),
 ('Seven Samurai', ' 0.27M'),
 ('Ran', ' 4.14M'),
 ('Raiders of the Lost Ark', ' 248.16M'),
 ('Raatchasan', 'NA'),
 ('Princess Mononoke', ' 2.38M'),
 ('Oldboy', ' 0.71M'),
 ('North by Northwest', ' 13.28M'),
 ('LÃ©on: The Professional', ' 19.50M'),
 ('Kill Bill: Vol. 1', ' 70.10M'),
 ('Kantara', 'NA'),
 ('Kaithi', 'NA'),
 ('K.G.F: Chapter 2', ' 6.60M'),
 ('Jurassic Park', ' 402.45M'),
 ('Indiana Jones and the Last Crusade', ' 197.17M'),
 ('Inception', ' 292.58M'),
 ('Heat', ' 67.44M'),
 ('Harakiri', 'NA'),
 ('Gladiator', ' 187.71M'),
 ('Gangs of Wasseypur', 'NA'),
 ('Die Hard', ' 83.01M'),
 ('Demon Slayer the Movie: Mugen Train', ' 47.70M'),
 ('Dangal', ' 12.39M'),
 ('Batman Begins', ' 206.85M'),
 ('Baahubali 2: The Conclusion', ' 20.19M'),
 ('Avengers: Infinity War', ' 678.82M'),
 ('Avengers: Endgame', ' 858.37M'),
 ('Asuran', 'NA'),
 ('Aliens', ' 85.16M'),
 ('1917', ' 159.23M')]

In [3]:
# 4) Display the gross collection of movies with the star Arnold.
results1=cur.execute('select sum(Gross),Stars1 from B where Stars1 like "Arnold%"')
results1.fetchall()

[(204.84, 'Arnold Schwarzenegger')]

In [40]:
# 5) Display all details of movies with comedy and action genres.
results1=cur.execute('select * from B where Genre1="Action" and Genre2="Comedy"')
results1.fetchall()

[('Gangs of Wasseypur',
  'Manoj Bajpayee',
  'Nawazuddin Siddiqui',
  'Tigmanshu Dhulia',
  99958,
  'Action',
  'Comedy',
  'Crime',
  'NA',
  'NA',
  'Not Rated\n')]

In [18]:
dbcon.commit()

In [41]:
# 1) Display all details from both tables where movie names are the same.
results2=cur.execute("select * from A join B on A.MovieName=B.MovieName")
results2.fetchall()

[(1,
  'The Dark Knight',
  'Christopher Nolan',
  'NA',
  'NA',
  152,
  2008,
  9.0,
  84,
  'The Dark Knight',
  'Christian Bale',
  'Heath Ledger',
  'Aaron Eckhart',
  2746898,
  'Action',
  'Crime',
  'Drama',
  ' 534.86M',
  39,
  'PG-13\n'),
 (2,
  'The Lord of the Rings: The Return of the King',
  'Peter Jackson',
  'NA',
  'NA',
  201,
  2003,
  9.0,
  94,
  'The Lord of the Rings: The Return of the King',
  'Elijah Wood',
  'Viggo Mortensen',
  'Ian McKellen',
  1901241,
  'Action',
  'Adventure',
  'Drama',
  ' 377.85M',
  311,
  'PG-13\n'),
 (3,
  'Spider-Man: Across the Spider-Verse',
  'Joaquim Dos Santos',
  'Kemp Powers',
  'Justin K. Thompson',
  140,
  2023,
  8.9,
  86,
  'Spider-Man: Across the Spider-Verse',
  'Shameik Moore',
  'Hailee Steinfeld',
  'Brian Tyree Henry',
  191438,
  'Animation',
  'Action',
  'Adventure',
  'NA',
  13,
  'PG\n'),
 (4,
  'Inception',
  'Christopher Nolan',
  'NA',
  'NA',
  148,
  2010,
  8.8,
  74,
  'Inception',
  'Leonardo DiCaprio',
  'Joseph Gordon-Levitt',
  'Elliot Page',
  2437787,
  'Action',
  'Adventure',
  'Sci-Fi',
  ' 292.58M',
  43,
  'PG-13\n'),
 (5,
  'The Lord of the Rings: The Fellowship of the Ring',
  'Peter Jackson',
  'NA',
  'NA',
  178,
  2001,
  8.8,
  92,
  'The Lord of the Rings: The Fellowship of the Ring',
  'Elijah Wood',
  'Ian McKellen',
  'Orlando Bloom',
  1929591,
  'Action',
  'Adventure',
  'Drama',
  ' 315.54M',
  152,
  'PG-13\n'),
 (6,
  'The Lord of the Rings: The Two Towers',
  'Peter Jackson',
  'NA',
  'NA',
  179,
  2002,
  8.8,
  87,
  'The Lord of the Rings: The Two Towers',
  'Elijah Wood',
  'Ian McKellen',
  'Viggo Mortensen',
  1715719,
  'Action',
  'Adventure',
  'Drama',
  ' 342.55M',
  541,
  'PG-13\n'),
 (7,
  'The Matrix',
  'Lana Wachowski',
  'Lilly Wachowski',
  'NA',
  136,
  1999,
  8.7,
  73,
  'The Matrix',
  'Keanu Reeves',
  'Laurence Fishburne',
  'Carrie-Anne Moss',
  1973481,
  'Action',
  'Sci-Fi',
  'NA',
  ' 171.48M',
  201,
  'R\n'),
 (8,
  'Star Wars: Episode V - The Empire Strikes Back',
  'Irvin Kershner',
  'NA',
  'NA',
  124,
  1980,
  8.7,
  82,
  'Star Wars: Episode V - The Empire Strikes Back',
  'Mark Hamill',
  'Harrison Ford',
  'Carrie Fisher',
  1331313,
  'Action',
  'Adventure',
  'Fantasy',
  ' 290.48M',
  898,
  'PG\n'),
 (9,
  'Soorarai Pottru',
  'Sudha Kongara',
  'NA',
  'NA',
  153,
  2020,
  8.7,
  'NA\n',
  'Soorarai Pottru',
  'Suriya',
  'Paresh Rawal',
  'Aparna Balamurali',
  120110,
  'Action',
  'Drama',
  'NA',
  'NA',
  'NA',
  'TV-MA\n'),
 (10,
  'Terminator 2: Judgment Day',
  'James Cameron',
  'NA',
  'NA',
  137,
  1991,
  8.6,
  75,
  'Terminator 2: Judgment Day',
  'Arnold Schwarzenegger',
  'Linda Hamilton',
  'Edward Furlong',
  1132377,
  'Action',
  'Sci-Fi',
  'NA',
  ' 204.84M',
  249,
  'R\n'),
 (11,
  'Star Wars: Episode IV - A New Hope',
  'George Lucas',
  'NA',
  'NA',
  121,
  1977,
  8.6,
  90,
  'Star Wars: Episode IV - A New Hope',
  'Mark Hamill',
  'Harrison Ford',
  'Carrie Fisher',
  1403503,
  'Action',
  'Adventure',
  'Fantasy',
  ' 322.74M',
  344,
  'PG\n'),
 (12,
  'Seven Samurai',
  'Akira Kurosawa',
  'NA',
  'NA',
  207,
  1954,
  8.6,
  98,
  'Seven Samurai',
  'ToshirÃ´ Mifune',
  'Takashi Shimura',
  'Keiko Tsushima',
  355314,
  'Action',
  'Drama',
  'NA',
  ' 0.27M',
  1598,
  'Not Rated\n'),
 (13,
  'Harakiri',
  'Masaki Kobayashi',
  'NA',
  'NA',
  133,
  1962,
  8.6,
  85,
  'Harakiri',
  'Tatsuya Nakadai',
  'Akira Ishihama',
  'Shima Iwashita',
  62337,
  'Action',
  'Drama',
  'Mystery',
  'NA',
  2653,
  'Not Rated\n'),
 (14,
  'Sita Ramam',
  'Hanu Raghavapudi',
  'NA',
  'NA',
  163,
  2022,
  8.6,
  'NA\n',
  'Sita Ramam',
  'Dulquer Salmaan',
  'Mrunal Thakur',
  'Rashmika Mandanna',
  61561,
  'Action',
  'Drama',
  'Mystery',
  'NA',
  'NA',
  'NA\n'),
 (15,
  'Gladiator',
  'Ridley Scott',
  'NA',
  'NA',
  155,
  2000,
  8.5,
  67,
  'Gladiator',
  'Russell Crowe',
  'Joaquin Phoenix',
  'Connie Nielsen',
  1548002,
  'Action',
  'Adventure',
  'Drama',
  ' 187.71M',
  161,
  'R\n'),
 (16,
  'LÃ©on: The Professional',
  'Luc Besson',
  'NA',
  'NA',
  110,
  1994,
  8.5,
  64,
  'LÃ©on: The Professional',
  'Jean Reno',
  'Gary Oldman',
  'Natalie Portman',
  1198846,
  'Action',
  'Crime',
  'Drama',
  ' 19.50M',
  241,
  'R\n'),
 (17,
  'Raiders of the Lost Ark',
  'Steven Spielberg',
  'NA',
  'NA',
  115,
  1981,
  8.4,
  85,
  'Raiders of the Lost Ark',
  'Harrison Ford',
  'Karen Allen',
  'Paul Freeman',
  1005023,
  'Action',
  'Adventure',
  'NA',
  ' 248.16M',
  71,
  'PG\n'),
 (18,
  'Spider-Man: Into the Spider-Verse',
  'Bob Persichetti',
  'Peter Ramsey',
  'Rodney Rothman',
  117,
  2018,
  8.4,
  87,
  'Spider-Man: Into the Spider-Verse',
  'Shameik Moore',
  'Jake Johnson',
  'Hailee Steinfeld',
  611920,
  'Animation',
  'Action',
  'Adventure',
  ' 190.24M',
  89,
  'PG\n'),
 (19,
  'The Dark Knight Rises',
  'Christopher Nolan',
  'NA',
  'NA',
  164,
  2012,
  8.4,
  78,
  'The Dark Knight Rises',
  'Christian Bale',
  'Tom Hardy',
  'Anne Hathaway',
  1757420,
  'Action',
  'Drama',
  'Thriller',
  ' 448.14M',
  111,
  'PG-13\n'),
 (20,
  'Avengers: Endgame',
  'Anthony Russo',
  'Joe Russo',
  'NA',
  181,
  2019,
  8.4,
  78,
  'Avengers: Endgame',
  'Robert Downey Jr.',
  'Chris Evans',
  'Mark Ruffalo',
  1197274,
  'Action',
  'Adventure',
  'Drama',
  ' 858.37M',
  155,
  'PG-13\n'),
 (21,
  'Aliens',
  'James Cameron',
  'NA',
  'NA',
  137,
  1986,
  8.4,
  84,
  'Aliens',
  'Sigourney Weaver',
  'Michael Biehn',
  'Carrie Henn',
  737743,
  'Action',
  'Adventure',
  'Sci-Fi',
  ' 85.16M',
  180,
  'R\n'),
 (22,
  'Oldboy',
  'Park Chan-wook',
  'NA',
  'NA',
  101,
  2003,
  8.4,
  77,
  'Oldboy',
  'Choi Min-sik',
  'Yoo Ji-tae',
  'Kang Hye-jeong',
  602343,
  'Action',
  'Drama',
  'Mystery',
  ' 0.71M',
  264,
  'R\n'),
 (23,
  'Avengers: Infinity War',
  'Anthony Russo',
  'Joe Russo',
  'NA',
  149,
  2018,
  8.4,
  68,
  'Avengers: Infinity War',
  'Robert Downey Jr.',
  'Chris Hemsworth',
  'Mark Ruffalo',
  1139385,
  'Action',
  'Adventure',
  'Sci-Fi',
  ' 678.82M',
  370,
  'PG-13\n'),
 (24,
  'Kaithi',
  'Lokesh Kanagaraj',
  'NA',
  'NA',
  145,
  2019,
  8.4,
  'NA\n',
  'Kaithi',
  'Karthi',
  'Narain',
  'Arjun Das',
  36857,
  'Action',
  'Adventure',
  'Crime',
  'NA',
  'NA',
  'Not Rated\n'),
 (25,
  'Asuran',
  'Vetrimaaran',
  'NA',
  'NA',
  141,
  2019,
  8.4,
  'NA\n',
  'Asuran',
  'Dhanush',
  'Manju Warrier',
  'Prakash Raj',
  31567,
  'Action',
  'Drama',
  'NA',
  'NA',
  'NA',
  'Not Rated\n'),
 (26,
  'Top Gun: Maverick',
  'Joseph Kosinski',
  'NA',
  'NA',
  130,
  2022,
  8.3,
  78,
  'Top Gun: Maverick',
  'Tom Cruise',
  'Jennifer Connelly',
  'Miles Teller',
  612778,
  'Action',
  'Drama',
  'NA',
  ' 718.73M',
  55,
  'PG-13\n'),
 (27,
  'Heat',
  'Michael Mann',
  'NA',
  'NA',
  170,
  1995,
  8.3,
  76,
  'Heat',
  'Al Pacino',
  'Robert De Niro',
  'Val Kilmer',
  684205,
  'Action',
  'Crime',
  'Drama',
  ' 67.44M',
  140,
  'R\n'),
 (28,
  'Star Wars: Episode VI - Return of the Jedi',
  'Richard Marquand',
  'NA',
  'NA',
  131,
  1983,
  8.3,
  58,
  'Star Wars: Episode VI - Return of the Jedi',
  'Mark Hamill',
  'Harrison Ford',
  'Carrie Fisher',
  1085357,
  'Action',
  'Adventure',
  'Fantasy',
  ' 309.13M',
  1056,
  'PG\n'),
 (29,
  'Princess Mononoke',
  'Hayao Miyazaki',
  'NA',
  'NA',
  134,
  1997,
  8.3,
  76,
  'Princess Mononoke',
  'YÃ´ji Matsuda',
  'Yuriko Ishida',
  'YÃ»ko Tanaka',
  410961,
  'Animation',
  'Action',
  'Adventure',
  ' 2.38M',
  1132,
  'PG-13\n'),
 (30,
  'North by Northwest',
  'Alfred Hitchcock',
  'NA',
  'NA',
  136,
  1959,
  8.3,
  98,
  'North by Northwest',
  'Cary Grant',
  'Eva Marie Saint',
  'James Mason',
  336675,
  'Action',
  'Adventure',
  'Mystery',
  ' 13.28M',
  2349,
  'Approved\n'),
 (31,
  'Dangal',
  'Nitesh Tiwari',
  'NA',
  'NA',
  161,
  2016,
  8.3,
  'NA\n',
  'Dangal',
  'Aamir Khan',
  'Sakshi Tanwar',
  'Fatima Sana Shaikh',
  199361,
  'Action',
  'Biography',
  'Drama',
  ' 12.39M',
  3482,
  'Not Rated\n'),
 (32,
  'Kantara',
  'Rishab Shetty',
  'NA',
  'NA',
  148,
  2022,
  8.3,
  'NA\n',
  'Kantara',
  'Rishab Shetty',
  'Kishore Kumar G.',
  'Achyuth Kumar',
  96994,
  'Action',
  'Adventure',
  'Drama',
  'NA',
  4571,
  'Not Rated\n'),
 (33,
  'K.G.F: Chapter 2',
  'Prashanth Neel',
  'NA',
  'NA',
  168,
  2022,
  8.3,
  'NA\n',
  'K.G.F: Chapter 2',
  'Yash',
  'Sanjay Dutt',
  'Raveena Tandon',
  141171,
  'Action',
  'Crime',
  'Drama',
  ' 6.60M',
  'NA',
  'Not Rated\n'),
 (34,
  'Vikram',
  'Lokesh Kanagaraj',
  'NA',
  'NA',
  175,
  2022,
  8.3,
  'NA\n',
  'Vikram',
  'Kamal Haasan',
  'Vijay Sethupathi',
  'Fahadh Faasil',
  64888,
  'Action',
  'Crime',
  'Thriller',
  'NA',
  'NA',
  'NA\n'),
 (35,
  'Shershaah',
  'Vishnuvardhan',
  'NA',
  'NA',
  135,
  2021,
  8.3,
  'NA\n',
  'Shershaah',
  'Sidharth Malhotra',
  'Kiara Advani',
  'Shiv Panditt',
  125646,
  'Action',
  'Biography',
  'Drama',
  'NA',
  'NA',
  'TV-14\n'),
 (36,
  'Raatchasan',
  'Ram Kumar',
  'NA',
  'NA',
  170,
  2018,
  8.3,
  'NA\n',
  'Raatchasan',
  'Vishnu Vishal',
  'Amala Paul',
  'Radha Ravi',
  47541,
  'Action',
  'Crime',
  'Drama',
  'NA',
  'NA',
  'Not Rated\n'),
 (37,
  'Indiana Jones and the Last Crusade',
  'Steven Spielberg',
  'NA',
  'NA',
  127,
  1989,
  8.2,
  65,
  'Indiana Jones and the Last Crusade',
  'Harrison Ford',
  'Sean Connery',
  'Alison Doody',
  785231,
  'Action',
  'Adventure',
  'NA',
  ' 197.17M',
  104,
  'PG-13\n'),
 (38,
  'Jurassic Park',
  'Steven Spielberg',
  'NA',
  'NA',
  127,
  1993,
  8.2,
  68,
  'Jurassic Park',
  'Sam Neill',
  'Laura Dern',
  'Jeff Goldblum',
  1024335,
  'Action',
  'Adventure',
  'Sci-Fi',
  ' 402.45M',
  121,
  'PG-13\n'),
 (39,
  'Batman Begins',
  'Christopher Nolan',
  'NA',
  'NA',
  140,
  2005,
  8.2,
  70,
  'Batman Begins',
  'Christian Bale',
  'Michael Caine',
  'Ken Watanabe',
  1517368,
  'Action',
  'Crime',
  'Drama',
  ' 206.85M',
  128,
  'PG-13\n'),
 (40,
  'Spider-Man: No Way Home',
  'Jon Watts',
  'NA',
  'NA',
  148,
  2021,
  8.2,
  71,
  'Spider-Man: No Way Home',
  'Tom Holland',
  'Zendaya',
  'Benedict Cumberbatch',
  815853,
  'Action',
  'Adventure',
  'Fantasy',
  ' 804.75M',
  132,
  'PG-13\n'),
 (41,
  '1917',
  'Sam Mendes',
  'NA',
  'NA',
  119,
  2019,
  8.2,
  78,
  '1917',
  'Dean-Charles Chapman',
  'George MacKay',
  'Daniel Mays',
  631012,
  'Action',
  'Drama',
  'War',
  ' 159.23M',
  305,
  'R\n'),
 (42,
  'Die Hard',
  'John McTiernan',
  'NA',
  'NA',
  132,
  1988,
  8.2,
  72,
  'Die Hard',
  'Bruce Willis',
  'Alan Rickman',
  'Bonnie Bedelia',
  906945,
  'Action',
  'Thriller',
  'NA',
  ' 83.01M',
  413,
  'R\n'),
 (43,
  'Kill Bill: Vol. 1',
  'Quentin Tarantino',
  'NA',
  'NA',
  111,
  2003,
  8.2,
  69,
  'Kill Bill: Vol. 1',
  'Uma Thurman',
  'David Carradine',
  'Daryl Hannah',
  1148879,
  'Action',
  'Crime',
  'Thriller',
  ' 70.10M',
  587,
  'R\n'),
 (44,
  'V for Vendetta',
  'James McTeigue',
  'NA',
  'NA',
  132,
  2005,
  8.2,
  62,
  'V for Vendetta',
  'Hugo Weaving',
  'Natalie Portman',
  'Rupert Graves',
  1146896,
  'Action',
  'Drama',
  'Sci-Fi',
  ' 70.51M',
  971,
  'R\n'),
 (45,
  'Ran',
  'Akira Kurosawa',
  'NA',
  'NA',
  162,
  1985,
  8.2,
  97,
  'Ran',
  'Tatsuya Nakadai',
  'Akira Terao',
  'Jinpachi Nezu',
  130495,
  'Action',
  'Drama',
  'War',
  ' 4.14M',
  2298,
  'R\n'),
 (46,
  'Demon Slayer the Movie: Mugen Train',
  'Haruo Sotozaki',
  'NA',
  'NA',
  117,
  2020,
  8.2,
  72,
  'Demon Slayer the Movie: Mugen Train',
  'Natsuki Hanae',
  'Akari KitÃ´',
  'Yoshitsugu Matsuoka',
  66279,
  'Animation',
  'Action',
  'Adventure',
  ' 47.70M',
  3130,
  'TV-14\n'),
 (47,
  'Baahubali 2: The Conclusion',
  'S.S. Rajamouli',
  'NA',
  'NA',
  167,
  2017,
  8.2,
  'NA\n',
  'Baahubali 2: The Conclusion',
  'Prabhas',
  'Rana Daggubati',
  'Anushka Shetty',
  108203,
  'Action',
  'Drama',
  'NA',
  ' 20.19M',
  4610,
  'Not Rated\n'),
 (48,
  'Gangs of Wasseypur',
  'Anurag Kashyap',
  'NA',
  'NA',
  321,
  2012,
  8.2,
  89,
  'Gangs of Wasseypur',
  'Manoj Bajpayee',
  'Nawazuddin Siddiqui',
  'Tigmanshu Dhulia',
  99958,
  'Action',
  'Comedy',
  'Crime',
  'NA',
  'NA',
  'Not Rated\n'),
 (49,
  'Yojimbo',
  'Akira Kurosawa',
  'NA',
  'NA',
  110,
  1961,
  8.2,
  93,
  'Yojimbo',
  'ToshirÃ´ Mifune',
  'EijirÃ´ TÃ´no',
  'Tatsuya Nakadai',
  126865,
  'Action',
  'Drama',
  'Thriller',
  'NA',
  'NA',
  'Not Rated\n'),
 (50,
  'Uri: The Surgical Strike',
  'Aditya Dhar',
  'NA',
  'NA',
  138,
  2019,
  8.2,
  'NA\n',
  'Uri: The Surgical Strike',
  'Vicky Kaushal',
  'Paresh Rawal',
  'Mohit Raina',
  68404,
  'Action',
  'Drama',
  'History',
  ' 4.19M',
  'NA',
  'Not Rated\n')]

In [61]:
# 2)   Display all movie names, Director, ratings, and gross collection where the genre is action.
results2=cur.execute("SELECT A.MovieName,A.Director1,A.Director2,A.Director3, A.Ratings, B.Gross from A  join B on A.MovieName=B.MovieName WHERE Genre1='Action'")
results2.fetchall()

[('The Dark Knight', 'Christopher Nolan', 'NA', 'NA', 9.0, ' 534.86M'),
 ('The Lord of the Rings: The Return of the King',
  'Peter Jackson',
  'NA',
  'NA',
  9.0,
  ' 377.85M'),
 ('Inception', 'Christopher Nolan', 'NA', 'NA', 8.8, ' 292.58M'),
 ('The Lord of the Rings: The Fellowship of the Ring',
  'Peter Jackson',
  'NA',
  'NA',
  8.8,
  ' 315.54M'),
 ('The Lord of the Rings: The Two Towers',
  'Peter Jackson',
  'NA',
  'NA',
  8.8,
  ' 342.55M'),
 ('The Matrix', 'Lana Wachowski', 'Lilly Wachowski', 'NA', 8.7, ' 171.48M'),
 ('Star Wars: Episode V - The Empire Strikes Back',
  'Irvin Kershner',
  'NA',
  'NA',
  8.7,
  ' 290.48M'),
 ('Soorarai Pottru', 'Sudha Kongara', 'NA', 'NA', 8.7, 'NA'),
 ('Terminator 2: Judgment Day', 'James Cameron', 'NA', 'NA', 8.6, ' 204.84M'),
 ('Star Wars: Episode IV - A New Hope',
  'George Lucas',
  'NA',
  'NA',
  8.6,
  ' 322.74M'),
 ('Seven Samurai', 'Akira Kurosawa', 'NA', 'NA', 8.6, ' 0.27M'),
 ('Harakiri', 'Masaki Kobayashi', 'NA', 'NA', 8.6, 'NA'),
 ('Sita Ramam', 'Hanu Raghavapudi', 'NA', 'NA', 8.6, 'NA'),
 ('Gladiator', 'Ridley Scott', 'NA', 'NA', 8.5, ' 187.71M'),
 ('LÃ©on: The Professional', 'Luc Besson', 'NA', 'NA', 8.5, ' 19.50M'),
 ('Raiders of the Lost Ark', 'Steven Spielberg', 'NA', 'NA', 8.4, ' 248.16M'),
 ('The Dark Knight Rises', 'Christopher Nolan', 'NA', 'NA', 8.4, ' 448.14M'),
 ('Avengers: Endgame', 'Anthony Russo', 'Joe Russo', 'NA', 8.4, ' 858.37M'),
 ('Aliens', 'James Cameron', 'NA', 'NA', 8.4, ' 85.16M'),
 ('Oldboy', 'Park Chan-wook', 'NA', 'NA', 8.4, ' 0.71M'),
 ('Avengers: Infinity War',
  'Anthony Russo',
  'Joe Russo',
  'NA',
  8.4,
  ' 678.82M'),
 ('Kaithi', 'Lokesh Kanagaraj', 'NA', 'NA', 8.4, 'NA'),
 ('Asuran', 'Vetrimaaran', 'NA', 'NA', 8.4, 'NA'),
 ('Top Gun: Maverick', 'Joseph Kosinski', 'NA', 'NA', 8.3, ' 718.73M'),
 ('Heat', 'Michael Mann', 'NA', 'NA', 8.3, ' 67.44M'),
 ('Star Wars: Episode VI - Return of the Jedi',
  'Richard Marquand',
  'NA',
  'NA',
  8.3,
  ' 309.13M'),
 ('North by Northwest', 'Alfred Hitchcock', 'NA', 'NA', 8.3, ' 13.28M'),
 ('Dangal', 'Nitesh Tiwari', 'NA', 'NA', 8.3, ' 12.39M'),
 ('Kantara', 'Rishab Shetty', 'NA', 'NA', 8.3, 'NA'),
 ('K.G.F: Chapter 2', 'Prashanth Neel', 'NA', 'NA', 8.3, ' 6.60M'),
 ('Vikram', 'Lokesh Kanagaraj', 'NA', 'NA', 8.3, 'NA'),
 ('Shershaah', 'Vishnuvardhan', 'NA', 'NA', 8.3, 'NA'),
 ('Raatchasan', 'Ram Kumar', 'NA', 'NA', 8.3, 'NA'),
 ('Indiana Jones and the Last Crusade',
  'Steven Spielberg',
  'NA',
  'NA',
  8.2,
  ' 197.17M'),
 ('Jurassic Park', 'Steven Spielberg', 'NA', 'NA', 8.2, ' 402.45M'),
 ('Batman Begins', 'Christopher Nolan', 'NA', 'NA', 8.2, ' 206.85M'),
 ('Spider-Man: No Way Home', 'Jon Watts', 'NA', 'NA', 8.2, ' 804.75M'),
 ('1917', 'Sam Mendes', 'NA', 'NA', 8.2, ' 159.23M'),
 ('Die Hard', 'John McTiernan', 'NA', 'NA', 8.2, ' 83.01M'),
 ('Kill Bill: Vol. 1', 'Quentin Tarantino', 'NA', 'NA', 8.2, ' 70.10M'),
 ('V for Vendetta', 'James McTeigue', 'NA', 'NA', 8.2, ' 70.51M'),
 ('Ran', 'Akira Kurosawa', 'NA', 'NA', 8.2, ' 4.14M'),
 ('Baahubali 2: The Conclusion', 'S.S. Rajamouli', 'NA', 'NA', 8.2, ' 20.19M'),
 ('Gangs of Wasseypur', 'Anurag Kashyap', 'NA', 'NA', 8.2, 'NA'),
 ('Yojimbo', 'Akira Kurosawa', 'NA', 'NA', 8.2, 'NA'),
 ('Uri: The Surgical Strike', 'Aditya Dhar', 'NA', 'NA', 8.2, ' 4.19M')]

In [62]:
# 3) Display all details from both tables with the highest gross collection.
results2=cur.execute('select * from A join B on A.MovieName=B.MovieName where B.Gross=(select max(Gross) from B)')
results2.fetchall()

[(3,
  'Spider-Man: Across the Spider-Verse',
  'Joaquim Dos Santos',
  'Kemp Powers',
  'Justin K. Thompson',
  140,
  2023,
  8.9,
  86,
  'Spider-Man: Across the Spider-Verse',
  'Shameik Moore',
  'Hailee Steinfeld',
  'Brian Tyree Henry',
  191438,
  'Animation',
  'Action',
  'Adventure',
  'NA',
  13,
  'PG\n'),
 (9,
  'Soorarai Pottru',
  'Sudha Kongara',
  'NA',
  'NA',
  153,
  2020,
  8.7,
  'NA\n',
  'Soorarai Pottru',
  'Suriya',
  'Paresh Rawal',
  'Aparna Balamurali',
  120110,
  'Action',
  'Drama',
  'NA',
  'NA',
  'NA',
  'TV-MA\n'),
 (13,
  'Harakiri',
  'Masaki Kobayashi',
  'NA',
  'NA',
  133,
  1962,
  8.6,
  85,
  'Harakiri',
  'Tatsuya Nakadai',
  'Akira Ishihama',
  'Shima Iwashita',
  62337,
  'Action',
  'Drama',
  'Mystery',
  'NA',
  2653,
  'Not Rated\n'),
 (14,
  'Sita Ramam',
  'Hanu Raghavapudi',
  'NA',
  'NA',
  163,
  2022,
  8.6,
  'NA\n',
  'Sita Ramam',
  'Dulquer Salmaan',
  'Mrunal Thakur',
  'Rashmika Mandanna',
  61561,
  'Action',
  'Drama',
  'Mystery',
  'NA',
  'NA',
  'NA\n'),
 (24,
  'Kaithi',
  'Lokesh Kanagaraj',
  'NA',
  'NA',
  145,
  2019,
  8.4,
  'NA\n',
  'Kaithi',
  'Karthi',
  'Narain',
  'Arjun Das',
  36857,
  'Action',
  'Adventure',
  'Crime',
  'NA',
  'NA',
  'Not Rated\n'),
 (25,
  'Asuran',
  'Vetrimaaran',
  'NA',
  'NA',
  141,
  2019,
  8.4,
  'NA\n',
  'Asuran',
  'Dhanush',
  'Manju Warrier',
  'Prakash Raj',
  31567,
  'Action',
  'Drama',
  'NA',
  'NA',
  'NA',
  'Not Rated\n'),
 (32,
  'Kantara',
  'Rishab Shetty',
  'NA',
  'NA',
  148,
  2022,
  8.3,
  'NA\n',
  'Kantara',
  'Rishab Shetty',
  'Kishore Kumar G.',
  'Achyuth Kumar',
  96994,
  'Action',
  'Adventure',
  'Drama',
  'NA',
  4571,
  'Not Rated\n'),
 (34,
  'Vikram',
  'Lokesh Kanagaraj',
  'NA',
  'NA',
  175,
  2022,
  8.3,
  'NA\n',
  'Vikram',
  'Kamal Haasan',
  'Vijay Sethupathi',
  'Fahadh Faasil',
  64888,
  'Action',
  'Crime',
  'Thriller',
  'NA',
  'NA',
  'NA\n'),
 (35,
  'Shershaah',
  'Vishnuvardhan',
  'NA',
  'NA',
  135,
  2021,
  8.3,
  'NA\n',
  'Shershaah',
  'Sidharth Malhotra',
  'Kiara Advani',
  'Shiv Panditt',
  125646,
  'Action',
  'Biography',
  'Drama',
  'NA',
  'NA',
  'TV-14\n'),
 (36,
  'Raatchasan',
  'Ram Kumar',
  'NA',
  'NA',
  170,
  2018,
  8.3,
  'NA\n',
  'Raatchasan',
  'Vishnu Vishal',
  'Amala Paul',
  'Radha Ravi',
  47541,
  'Action',
  'Crime',
  'Drama',
  'NA',
  'NA',
  'Not Rated\n'),
 (48,
  'Gangs of Wasseypur',
  'Anurag Kashyap',
  'NA',
  'NA',
  321,
  2012,
  8.2,
  89,
  'Gangs of Wasseypur',
  'Manoj Bajpayee',
  'Nawazuddin Siddiqui',
  'Tigmanshu Dhulia',
  99958,
  'Action',
  'Comedy',
  'Crime',
  'NA',
  'NA',
  'Not Rated\n'),
 (49,
  'Yojimbo',
  'Akira Kurosawa',
  'NA',
  'NA',
  110,
  1961,
  8.2,
  93,
  'Yojimbo',
  'ToshirÃ´ Mifune',
  'EijirÃ´ TÃ´no',
  'Tatsuya Nakadai',
  126865,
  'Action',
  'Drama',
  'Thriller',
  'NA',
  'NA',
  'Not Rated\n')]

In [63]:
# 4) Display all details from both tables with the highest ratings
results2=cur.execute('select * from A join B on A.MovieName=B.MovieName where A.Ratings=(select max(Ratings) from A)')
results2.fetchall()

[(1,
  'The Dark Knight',
  'Christopher Nolan',
  'NA',
  'NA',
  152,
  2008,
  9.0,
  84,
  'The Dark Knight',
  'Christian Bale',
  'Heath Ledger',
  'Aaron Eckhart',
  2746898,
  'Action',
  'Crime',
  'Drama',
  ' 534.86M',
  39,
  'PG-13\n'),
 (2,
  'The Lord of the Rings: The Return of the King',
  'Peter Jackson',
  'NA',
  'NA',
  201,
  2003,
  9.0,
  94,
  'The Lord of the Rings: The Return of the King',
  'Elijah Wood',
  'Viggo Mortensen',
  'Ian McKellen',
  1901241,
  'Action',
  'Adventure',
  'Drama',
  ' 377.85M',
  311,
  'PG-13\n')]

In [66]:
# 5) Display all details from both tables with the lowest gross collection and lowest ratings
results2=cur.execute('select * from A join B on A.MovieName=B.MovieName where A.Ratings=(select min(Ratings) from A) or B.Gross=(select min(Gross) from B)')
results2.fetchall()

[(12,
  'Seven Samurai',
  'Akira Kurosawa',
  'NA',
  'NA',
  207,
  1954,
  8.6,
  98,
  'Seven Samurai',
  'ToshirÃ´ Mifune',
  'Takashi Shimura',
  'Keiko Tsushima',
  355314,
  'Action',
  'Drama',
  'NA',
  ' 0.27M',
  1598,
  'Not Rated\n'),
 (37,
  'Indiana Jones and the Last Crusade',
  'Steven Spielberg',
  'NA',
  'NA',
  127,
  1989,
  8.2,
  65,
  'Indiana Jones and the Last Crusade',
  'Harrison Ford',
  'Sean Connery',
  'Alison Doody',
  785231,
  'Action',
  'Adventure',
  'NA',
  ' 197.17M',
  104,
  'PG-13\n'),
 (38,
  'Jurassic Park',
  'Steven Spielberg',
  'NA',
  'NA',
  127,
  1993,
  8.2,
  68,
  'Jurassic Park',
  'Sam Neill',
  'Laura Dern',
  'Jeff Goldblum',
  1024335,
  'Action',
  'Adventure',
  'Sci-Fi',
  ' 402.45M',
  121,
  'PG-13\n'),
 (39,
  'Batman Begins',
  'Christopher Nolan',
  'NA',
  'NA',
  140,
  2005,
  8.2,
  70,
  'Batman Begins',
  'Christian Bale',
  'Michael Caine',
  'Ken Watanabe',
  1517368,
  'Action',
  'Crime',
  'Drama',
  ' 206.85M',
  128,
  'PG-13\n'),
 (40,
  'Spider-Man: No Way Home',
  'Jon Watts',
  'NA',
  'NA',
  148,
  2021,
  8.2,
  71,
  'Spider-Man: No Way Home',
  'Tom Holland',
  'Zendaya',
  'Benedict Cumberbatch',
  815853,
  'Action',
  'Adventure',
  'Fantasy',
  ' 804.75M',
  132,
  'PG-13\n'),
 (41,
  '1917',
  'Sam Mendes',
  'NA',
  'NA',
  119,
  2019,
  8.2,
  78,
  '1917',
  'Dean-Charles Chapman',
  'George MacKay',
  'Daniel Mays',
  631012,
  'Action',
  'Drama',
  'War',
  ' 159.23M',
  305,
  'R\n'),
 (42,
  'Die Hard',
  'John McTiernan',
  'NA',
  'NA',
  132,
  1988,
  8.2,
  72,
  'Die Hard',
  'Bruce Willis',
  'Alan Rickman',
  'Bonnie Bedelia',
  906945,
  'Action',
  'Thriller',
  'NA',
  ' 83.01M',
  413,
  'R\n'),
 (43,
  'Kill Bill: Vol. 1',
  'Quentin Tarantino',
  'NA',
  'NA',
  111,
  2003,
  8.2,
  69,
  'Kill Bill: Vol. 1',
  'Uma Thurman',
  'David Carradine',
  'Daryl Hannah',
  1148879,
  'Action',
  'Crime',
  'Thriller',
  ' 70.10M',
  587,
  'R\n'),
 (44,
  'V for Vendetta',
  'James McTeigue',
  'NA',
  'NA',
  132,
  2005,
  8.2,
  62,
  'V for Vendetta',
  'Hugo Weaving',
  'Natalie Portman',
  'Rupert Graves',
  1146896,
  'Action',
  'Drama',
  'Sci-Fi',
  ' 70.51M',
  971,
  'R\n'),
 (45,
  'Ran',
  'Akira Kurosawa',
  'NA',
  'NA',
  162,
  1985,
  8.2,
  97,
  'Ran',
  'Tatsuya Nakadai',
  'Akira Terao',
  'Jinpachi Nezu',
  130495,
  'Action',
  'Drama',
  'War',
  ' 4.14M',
  2298,
  'R\n'),
 (46,
  'Demon Slayer the Movie: Mugen Train',
  'Haruo Sotozaki',
  'NA',
  'NA',
  117,
  2020,
  8.2,
  72,
  'Demon Slayer the Movie: Mugen Train',
  'Natsuki Hanae',
  'Akari KitÃ´',
  'Yoshitsugu Matsuoka',
  66279,
  'Animation',
  'Action',
  'Adventure',
  ' 47.70M',
  3130,
  'TV-14\n'),
 (47,
  'Baahubali 2: The Conclusion',
  'S.S. Rajamouli',
  'NA',
  'NA',
  167,
  2017,
  8.2,
  'NA\n',
  'Baahubali 2: The Conclusion',
  'Prabhas',
  'Rana Daggubati',
  'Anushka Shetty',
  108203,
  'Action',
  'Drama',
  'NA',
  ' 20.19M',
  4610,
  'Not Rated\n'),
 (48,
  'Gangs of Wasseypur',
  'Anurag Kashyap',
  'NA',
  'NA',
  321,
  2012,
  8.2,
  89,
  'Gangs of Wasseypur',
  'Manoj Bajpayee',
  'Nawazuddin Siddiqui',
  'Tigmanshu Dhulia',
  99958,
  'Action',
  'Comedy',
  'Crime',
  'NA',
  'NA',
  'Not Rated\n'),
 (49,
  'Yojimbo',
  'Akira Kurosawa',
  'NA',
  'NA',
  110,
  1961,
  8.2,
  93,
  'Yojimbo',
  'ToshirÃ´ Mifune',
  'EijirÃ´ TÃ´no',
  'Tatsuya Nakadai',
  126865,
  'Action',
  'Drama',
  'Thriller',
  'NA',
  'NA',
  'Not Rated\n'),
 (50,
  'Uri: The Surgical Strike',
  'Aditya Dhar',
  'NA',
  'NA',
  138,
  2019,
  8.2,
  'NA\n',
  'Uri: The Surgical Strike',
  'Vicky Kaushal',
  'Paresh Rawal',
  'Mohit Raina',
  68404,
  'Action',
  'Drama',
  'History',
  ' 4.19M',
  'NA',
  'Not Rated\n')]

In [70]:
cur.close()

In [71]:
dbcon.close()